name: Simple Content Validation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Validate file structure
      run: |
        echo "🔍 Validating file structure..."
        if [ ! -f "index.html" ]; then
          echo "❌ index.html is missing"
          exit 1
        fi
        if [ ! -f "styles.css" ]; then
          echo "❌ styles.css is missing"
          exit 1
        fi
        if [ ! -f "script.js" ]; then
          echo "❌ script.js is missing"
          exit 1
        fi
        echo "✅ All required files present"
        
    - name: Check HTML syntax
      run: |
        echo "🔍 Checking HTML syntax..."
        # Basic HTML validation
        if ! grep -q "<!DOCTYPE html>" index.html; then
          echo "❌ Missing DOCTYPE declaration"
          exit 1
        fi
        if ! grep -q "<html" index.html; then
          echo "❌ Missing html tag"
          exit 1
        fi
        if ! grep -q "<head" index.html; then
          echo "❌ Missing head tag"
          exit 1
        fi
        if ! grep -q "<body" index.html; then
          echo "❌ Missing body tag"
          exit 1
        fi
        echo "✅ HTML structure is valid"
        
    - name: Check CSS syntax
      run: |
        echo "🔍 Checking CSS syntax..."
        # Basic CSS validation - check for common syntax errors
        if grep -q "{[^}]*$" styles.css; then
          echo "❌ Unclosed CSS braces detected"
          exit 1
        fi
        if grep -q ";[^}]*}" styles.css; then
          echo "❌ Missing semicolon before closing brace"
          exit 1
        fi
        echo "✅ CSS syntax appears valid"
        
    - name: Check JavaScript syntax
      run: |
        echo "🔍 Checking JavaScript syntax..."
        # Basic JS validation using node
        if ! node -c script.js; then
          echo "❌ JavaScript syntax error detected"
          exit 1
        fi
        echo "✅ JavaScript syntax is valid"
        
    - name: Check file sizes
      run: |
        echo "📊 Checking file sizes..."
        echo "HTML size: $(wc -c < index.html) bytes"
        echo "CSS size: $(wc -c < styles.css) bytes"
        echo "JS size: $(wc -c < script.js) bytes"
        
        # Warn if files are too large
        if [ $(wc -c < index.html) -gt 50000 ]; then
          echo "⚠️  HTML file is larger than 50KB"
        fi
        if [ $(wc -c < styles.css) -gt 100000 ]; then
          echo "⚠️  CSS file is larger than 100KB"
        fi
        if [ $(wc -c < script.js) -gt 50000 ]; then
          echo "⚠️  JavaScript file is larger than 50KB"
        fi
        
    - name: Check accessibility basics
      run: |
        echo "♿ Checking basic accessibility..."
        # Check for alt attributes on images
        if grep -q "<img" index.html && ! grep -q "alt=" index.html; then
          echo "⚠️  Images found without alt attributes"
        fi
        
        # Check for semantic HTML elements
        if ! grep -q "<main>" index.html; then
          echo "⚠️  No <main> element found"
        fi
        
        if ! grep -q "<nav>" index.html; then
          echo "⚠️  No <nav> element found"
        fi
        
        if ! grep -q "<header>" index.html; then
          echo "⚠️  No <header> element found"
        fi
        
        if ! grep -q "<footer>" index.html; then
          echo "⚠️  No <footer> element found"
        fi
        
        echo "✅ Basic accessibility checks completed"
        
    - name: Check for broken links
      run: |
        echo "🔗 Checking for broken links..."
        # Extract all links from HTML
        grep -o 'href="[^"]*"' index.html | sed 's/href="//;s/"$//' | while read link; do
          if [[ $link == http* ]]; then
            echo "Checking external link: $link"
            if ! curl -s --head "$link" > /dev/null; then
              echo "⚠️  Broken link detected: $link"
            fi
          fi
        done
        
    - name: Create validation summary
      run: |
        echo "## ✅ Validation Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Files Validated:" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ index.html" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ styles.css" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ script.js" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ README.md" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Checks Completed:" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ File structure validation" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ HTML syntax validation" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ CSS syntax validation" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ JavaScript syntax validation" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ File size analysis" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Basic accessibility checks" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Link validation" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "🎉 All validation checks passed!"